#!/usr/bin/env python3
"""Generate `app/src/main/res/values-b+en+001/translations.xml` — the British
English strings under a *qualified* locale — from `app/src/main/res/values/strings.xml`.

Why this file has to exist at all:

`values/strings.xml` is written in British English (it is Transifex's `en_GB`
source), but it carries no locale qualifier, so Android cannot tell it apart
from "the last resort". American English, meanwhile, is a translation like any
other and lives in `values-en-rUS`. A device set to English (Ireland) resolves
en-IE -> en-001 -> en, matches none of them, then falls back to "any resources
with the same language" — and the only `values-en*` dir is the American one.
Result: "Customize" and "Color" on an Irish, British, Australian, Indian or
South African phone.

`android:defaultLocale="en-GB"` in `res/xml/locales_config.xml` tells the system
the unqualified resources are en-GB, but that attribute is API 35+ and minSdk is
31, so it does nothing on Android 12-14. Shipping the same strings under
`values-b+en+001` fixes every supported version: en-001 ("world English") is the
CLDR parent of en-IE/en-GB/en-AU/en-IN/en-ZA, so all of them match it directly,
while en-US keeps matching `values-en-rUS`.

Why it is generated rather than hand-written: it is a byte-for-byte duplicate of
the source strings, and a duplicate maintained by hand drifts. Note that drift is
cheap here even if this file does go stale — a string missing from
`values-b+en+001` falls back to `values/strings.xml`, which holds the same
British text — so regenerating is about tidiness, not correctness.

Run after editing `values/strings.xml`; the weekly Transifex workflow re-runs it
too, so the file tracks the source without anyone remembering to.

    ./etc/generate_en_001_strings.py

Entries marked `translatable="false"` are skipped: they are URLs and font names,
identical in every locale, and duplicating them only gives the build more
resources to merge.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RES = REPO / 'app' / 'src' / 'main' / 'res'
SOURCE = RES / 'values' / 'strings.xml'
TARGET = RES / 'values-b+en+001' / 'translations.xml'

# Top-level resource elements, captured verbatim so that escapes (\', \n),
# inline markup (<b>, <xliff:g>) and <item> children survive untouched. The
# alternation puts string-array first: `string` alone would also match the start
# of `<string-array`, and the match would then run on to the next `</string>`.
ELEMENT = re.compile(
	r'<(string-array|plurals|string)\b[^>]*?(?:/>|>.*?</\1>)',
	re.DOTALL,
)
UNTRANSLATABLE = re.compile(r'\btranslatable\s*=\s*"false"')

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
	British English under a qualified locale, so that en-IE/en-GB/en-AU/en-IN/en-ZA
	stop falling back to the American values-en-rUS. en-001 is the CLDR parent of
	all of them; en-US is unaffected.

	GENERATED by etc/generate_en_001_strings.py from values/strings.xml.
	Do not hand-edit, and do not translate it on Transifex — re-run the script.
-->
<resources>
"""


def main() -> None:
	source = SOURCE.read_text(encoding='utf-8')
	elements = [
		match.group(0)
		for match in ELEMENT.finditer(source)
		if not UNTRANSLATABLE.search(match.group(0).split('>', 1)[0])
	]

	if not elements:
		raise SystemExit(f'No translatable resources found in {SOURCE}')

	body = '\n'.join('\t' + element.replace('\n    ', '\n\t') for element in elements)

	TARGET.parent.mkdir(parents=True, exist_ok=True)
	TARGET.write_text(f'{HEADER}{body}\n</resources>\n', encoding='utf-8')

	print(f'Wrote {len(elements)} resources to {TARGET.relative_to(REPO)}')


if __name__ == '__main__':
	main()
