apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

def properties = new Properties()
def secretFile = rootProject.file("secret.properties")
if (secretFile.exists()) {
    properties.load(new FileInputStream(secretFile))
}

android {
    namespace "be.robinj.distrohopper"
    compileSdkVersion 36
    defaultConfig {
        applicationId "be.robinj.distrohopper"
        minSdkVersion 29
        targetSdkVersion 36
        versionCode 101
        versionName "2.6.5"
        buildConfigField "String", "ACRA_USERNAME", "\"" + (properties['acra_username'] ?: "") + "\""
        buildConfigField "String", "ACRA_PASSWORD", "\"" + (properties['acra_password'] ?: "") + "\""
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        disable 'MissingTranslation', 'ExtraTranslation'
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

repositories {
    maven {
        url "http://repo.commonsware.com.s3.amazonaws.com"
        allowInsecureProtocol = true
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'asia.ivity.android:drag-sort-listview:1.0'
    implementation 'androidx.core:core-ktx:1.17.0'

    // ACRA
    def acraVersion = '5.5.1'
    implementation "ch.acra:acra-http:$acraVersion"
    implementation "ch.acra:acra-toast:$acraVersion"

    // Android instrumentation tests
    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
